services:
  - type: web
    name: fastapi-whatsapp-bot
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: WHATSAPP_TOKEN
        value: EAARtn5xSbEsBPDaNIAz2nhQyUwJ4cjMTtINcdy1o7IkLcLvuHFsMfk6ZBFpZAJAz5RL5Vz3lnWERTrdA4ZA2tZA85JLCwWAXsktLrSBm3KgacIHemDObEIj3gZBathVCVbvZAhbQ4TJseZAAs69Vnd9eZC2NGylC2tfpNMS4X9ATLF6jTCUfqSHmOUPrNZCvWkB5SSgZDZD
